export interface Option {
  key: 'A' | 'B' | 'C' | 'D';
  textEs: string;
  textHy: string;
}

export interface Question {
  id: number;
  part: 1 | 2 | 3 | 4 | 5;
  partTitleEs: string;
  partTitleHy: string;
  questionEs: string;
  questionHy: string;
  verb: string;
  options: Option[];
  correct: 'A' | 'B' | 'C' | 'D';
  explanationHy: string;
  hintHy: string;
  prizeValue: number;
  isMilestone?: boolean;
}

export const QUESTIONS: Question[] = [
  // --- Ronda 1 — ¿Qué hace un futbolista? (1-6) ---
  {
    id: 1,
    part: 1,
    partTitleEs: 'Ronda 1 — ¿Qué hace un futbolista?',
    partTitleHy: 'Փուլ 1 — Ի՞նչ է անում ֆուտբոլիստը (¿Qué hace un futbolista?)',
    questionEs: '¿Qué _____ un futbolista antes del partido?',
    questionHy: 'Ի՞նչ է անում ֆուտբոլիստը խաղից առաջ։',
    verb: 'hacer',
    options: [
      { key: 'A', textEs: 'hago', textHy: 'անում եմ (yo)' },
      { key: 'B', textEs: 'haces', textHy: 'անում ես (tú)' },
      { key: 'C', textEs: 'hace', textHy: 'անում է (él/ella)' },
      { key: 'D', textEs: 'hacemos', textHy: 'անում ենք (nosotros)' },
    ],
    correct: 'C',
    explanationHy: '«Un futbolista»-ն եզակի 3-րդ դեմք է (él/նա), ուստի «hacer» (անել) բայի ներկա ժամանակի ճիշտ ձևն է «hace»։',
    hintHy: 'Ենթական «ֆուտբոլիստը» է (él/նա)՝ պահանջում է եզակի 3-րդ դեմք (-e):',
    prizeValue: 500,
  },
  {
    id: 2,
    part: 1,
    partTitleEs: 'Ronda 1 — ¿Qué hace un futbolista?',
    partTitleHy: 'Փուլ 1 — Ի՞նչ է անում ֆուտբոլիստը (¿Qué hace un futbolista?)',
    questionEs: 'Yo _____ al fútbol todos los sábados.',
    questionHy: 'Ես ամեն շաբաթ ֆուտբոլ եմ խաղում։',
    verb: 'jugar',
    options: [
      { key: 'A', textEs: 'juego', textHy: 'խաղում եմ (yo)' },
      { key: 'B', textEs: 'juegas', textHy: 'խաղում ես (tú)' },
      { key: 'C', textEs: 'juega', textHy: 'խաղում է (él/ella)' },
      { key: 'D', textEs: 'jugamos', textHy: 'խաղում ենք (nosotros)' },
    ],
    correct: 'A',
    explanationHy: '«Yo» (ես) դերանվան հետ «jugar» (u -> ue) բայը ներկայում ստանում է «juego» ձևը (խաղում եմ)։',
    hintHy: '«Yo» (ես) դերանվան վերջավորությունն է «-o», իսկ արմատային u-ն դառնում է ue:',
    prizeValue: 1000,
  },
  {
    id: 3,
    part: 1,
    partTitleEs: 'Ronda 1 — ¿Qué hace un futbolista?',
    partTitleHy: 'Փուլ 1 — Ի՞նչ է անում ֆուտբոլիստը (¿Qué hace un futbolista?)',
    questionEs: 'Mi hermano _____ un balón nuevo.',
    questionHy: 'Եղբայրս նոր գնդակ ունի։',
    verb: 'tener',
    options: [
      { key: 'A', textEs: 'tengo', textHy: 'ունեմ (yo)' },
      { key: 'B', textEs: 'tienes', textHy: 'ունես (tú)' },
      { key: 'C', textEs: 'tenemos', textHy: 'ունենք (nosotros)' },
      { key: 'D', textEs: 'tiene', textHy: 'ունի (él/ella)' },
    ],
    correct: 'D',
    explanationHy: '«Mi hermano»-ն (եղբայրս) 3-րդ դեմք է (él), ուստի «tener» (ունենալ) բայը դառնում է «tiene»։',
    hintHy: '«Եղբայրս» (él) պահանջում է tener բայի 3-րդ դեմքի ձևը՝ «tiene»:',
    prizeValue: 2000,
  },
  {
    id: 4,
    part: 1,
    partTitleEs: 'Ronda 1 — ¿Qué hace un futbolista?',
    partTitleHy: 'Փուլ 1 — Ի՞նչ է անում ֆուտբոլիստը (¿Qué hace un futbolista?)',
    questionEs: 'Nosotros _____ al estadio los domingos.',
    questionHy: 'Մենք կիրակի օրերին գնում ենք մարզադաշտ։',
    verb: 'ir',
    options: [
      { key: 'A', textEs: 'voy', textHy: 'գնում եմ (yo)' },
      { key: 'B', textEs: 'vamos', textHy: 'գնում ենք (nosotros)' },
      { key: 'C', textEs: 'van', textHy: 'գնում են (ellos)' },
      { key: 'D', textEs: 'vas', textHy: 'գնում ես (tú)' },
    ],
    correct: 'B',
    explanationHy: '«Nosotros» (մենք) դերանվան դեպքում «ir» (գնալ) անկանոն բայի ձևն է «vamos» (գնում ենք)։',
    hintHy: '«Nosotros» (մենք) դերանվան համար ir բայի ձևն է «vamos»:',
    prizeValue: 3000,
  },
  {
    id: 5,
    part: 1,
    partTitleEs: 'Ronda 1 — ¿Qué hace un futbolista?',
    partTitleHy: 'Փուլ 1 — Ի՞նչ է անում ֆուտբոլիստը (¿Qué hace un futbolista?)',
    questionEs: '¿Tú _____ jugar de delantero o de defensa?',
    questionHy: 'Դու ուզո՞ւմ ես խաղալ հարձակվողի, թե՞ պաշտպանի դիրքում։',
    verb: 'querer',
    options: [
      { key: 'A', textEs: 'quiero', textHy: 'ուզում եմ (yo)' },
      { key: 'B', textEs: 'quiere', textHy: 'ուզում է (él/ella)' },
      { key: 'C', textEs: 'quieres', textHy: 'ուզում ես (tú)' },
      { key: 'D', textEs: 'queremos', textHy: 'ուզում ենք (nosotros)' },
    ],
    correct: 'C',
    explanationHy: '«Tú» (դու) դերանվան դեպքում «querer» (e -> ie) բայի ձևն է «quieres» (ուզում ես)։',
    hintHy: '«Tú» (դու) դերանվան վերջավորությունն է «-es»՝ quieres:',
    prizeValue: 5000,
    isMilestone: true,
  },
  {
    id: 6,
    part: 1,
    partTitleEs: 'Ronda 1 — ¿Qué hace un futbolista?',
    partTitleHy: 'Փուլ 1 — Ի՞նչ է անում ֆուտբոլիստը (¿Qué hace un futbolista?)',
    questionEs: 'Nuestro entrenador _____ muy responsable.',
    questionHy: 'Մեր մարզիչը շատ պատասխանատու է։',
    verb: 'ser',
    options: [
      { key: 'A', textEs: 'es', textHy: 'է (él/ella - ser)' },
      { key: 'B', textEs: 'está', textHy: 'գտնվում է (estar)' },
      { key: 'C', textEs: 'soy', textHy: 'եմ (yo - ser)' },
      { key: 'D', textEs: 'eres', textHy: 'ես (tú - ser)' },
    ],
    correct: 'A',
    explanationHy: 'Բնավորության/որակի մշտական հատկանիշի համար գործածվում է «ser» բայը, իսկ «nuestro entrenador»-ը él է՝ «es» (է)։',
    hintHy: '«Մարզիչը» él է, իսկ պատասխանատու լինելը մշտական հատկանիշ է (ser -> es):',
    prizeValue: 7500,
  },

  // --- Ronda 2 — Los verbos irregulares (7-12) ---
  {
    id: 7,
    part: 2,
    partTitleEs: 'Ronda 2 — Los verbos irregulares',
    partTitleHy: 'Փուլ 2 — Անկանոն բայեր (Los verbos irregulares)',
    questionEs: 'Yo no _____ correr diez kilómetros sin descansar.',
    questionHy: 'Ես չեմ կարող տասը կիլոմետր վազել առանց հանգստանալու։',
    verb: 'poder',
    options: [
      { key: 'A', textEs: 'puedes', textHy: 'կարող ես (tú)' },
      { key: 'B', textEs: 'puede', textHy: 'կարող է (él/ella)' },
      { key: 'C', textEs: 'podemos', textHy: 'կարող ենք (nosotros)' },
      { key: 'D', textEs: 'puedo', textHy: 'կարող եմ (yo)' },
    ],
    correct: 'D',
    explanationHy: '«Yo» (ես) դերանվան հետ «poder» (o -> ue) բայը դառնում է «puedo» (չեմ կարող՝ no puedo)։',
    hintHy: '«Yo»-ի հետ բայի վերջավորությունն է «-o», իսկ o-ն դառնում է ue՝ puedo:',
    prizeValue: 10000,
  },
  {
    id: 8,
    part: 2,
    partTitleEs: 'Ronda 2 — Los verbos irregulares',
    partTitleHy: 'Փուլ 2 — Անկանոն բայեր (Los verbos irregulares)',
    questionEs: '¿Tú _____ quién es Cristiano Ronaldo?',
    questionHy: 'Դու գիտե՞ս, թե ով է Կրիշտիանու Ռոնալդուն։',
    verb: 'saber',
    options: [
      { key: 'A', textEs: 'sé', textHy: 'գիտեմ (yo)' },
      { key: 'B', textEs: 'sabes', textHy: 'գիտես (tú)' },
      { key: 'C', textEs: 'sabe', textHy: 'գիտի (él/ella)' },
      { key: 'D', textEs: 'sabemos', textHy: 'գիտենք (nosotros)' },
    ],
    correct: 'B',
    explanationHy: '«Tú» (դու) դերանվան հետ «saber» (իմանալ/գիտենալ) բայը դառնում է «sabes» (գիտես)։',
    hintHy: '«Tú»-ի հետ saber բայը խոնարհվում է կանոնավոր վերջավորությամբ՝ sabes:',
    prizeValue: 15000,
  },
  {
    id: 9,
    part: 2,
    partTitleEs: 'Ronda 2 — Los verbos irregulares',
    partTitleHy: 'Փուլ 2 — Անկանոն բայեր (Los verbos irregulares)',
    questionEs: 'El entrenador _____ instrucciones antes del partido.',
    questionHy: 'Մարզիչը հրահանգներ է տալիս խաղից առաջ։',
    verb: 'dar',
    options: [
      { key: 'A', textEs: 'doy', textHy: 'տալիս եմ (yo)' },
      { key: 'B', textEs: 'das', textHy: 'տալիս ես (tú)' },
      { key: 'C', textEs: 'da', textHy: 'տալիս է (él/ella)' },
      { key: 'D', textEs: 'damos', textHy: 'տալիս ենք (nosotros)' },
    ],
    correct: 'C',
    explanationHy: '«El entrenador»-ը él է, ուստի «dar» (տալ) բայի 3-րդ դեմքի ձևն է «da» (տալիս է)։',
    hintHy: 'Dar բայի եզակի 3-րդ դեմքն է (él) «da»:',
    prizeValue: 20000,
  },
  {
    id: 10,
    part: 2,
    partTitleEs: 'Ronda 2 — Los verbos irregulares',
    partTitleHy: 'Փուլ 2 — Անկանոն բայեր (Los verbos irregulares)',
    questionEs: 'Mis amigos _____ a entrenar conmigo.',
    questionHy: 'Իմ ընկերները գալիս են ինձ հետ մարզվելու։',
    verb: 'venir',
    options: [
      { key: 'A', textEs: 'vienen', textHy: 'գալիս են (ellos)' },
      { key: 'B', textEs: 'venimos', textHy: 'գալիս ենք (nosotros)' },
      { key: 'C', textEs: 'viene', textHy: 'գալիս է (él/ella)' },
      { key: 'D', textEs: 'vengo', textHy: 'գալիս եմ (yo)' },
    ],
    correct: 'A',
    explanationHy: '«Mis amigos»-ը (ընկերներս) հոգնակի 3-րդ դեմք է (ellos/նրանք), ուստի «venir» բայը դառնում է «vienen»։',
    hintHy: '«Ընկերներս» (ellos) պահանջում է հոգնակի 3-րդ դեմք՝ «vienen»:',
    prizeValue: 25000,
    isMilestone: true,
  },
  {
    id: 11,
    part: 2,
    partTitleEs: 'Ronda 2 — Los verbos irregulares',
    partTitleHy: 'Փուլ 2 — Անկանոն բայեր (Los verbos irregulares)',
    questionEs: 'Yo _____ a muchos futbolistas famosos.',
    questionHy: 'Ես ճանաչում եմ բազմաթիվ հայտնի ֆուտբոլիստների։',
    verb: 'conocer',
    options: [
      { key: 'A', textEs: 'conoces', textHy: 'ճանաչում ես (tú)' },
      { key: 'B', textEs: 'conoce', textHy: 'ճանաչում է (él/ella)' },
      { key: 'C', textEs: 'conocemos', textHy: 'ճանաչում ենք (nosotros)' },
      { key: 'D', textEs: 'conozco', textHy: 'ճանաչում եմ (yo)' },
    ],
    correct: 'D',
    explanationHy: '«Conocer» բայը «yo» դերանվան հետ ունի անկանոն ձև՝ «conozco» (ճանաչում եմ)։',
    hintHy: '«Conocer»-ի 1-ին դեմքն ունի «-zco» վերջավորություն՝ conozco:',
    prizeValue: 35000,
  },
  {
    id: 12,
    part: 2,
    partTitleEs: 'Ronda 2 — Los verbos irregulares',
    partTitleHy: 'Փուլ 2 — Անկանոն բայեր (Los verbos irregulares)',
    questionEs: 'El entrenador nos _____ que debemos trabajar en equipo.',
    questionHy: 'Մարզիչը մեզ ասում է, որ պետք է թիմով աշխատենք։',
    verb: 'decir',
    options: [
      { key: 'A', textEs: 'digo', textHy: 'ասում եմ (yo)' },
      { key: 'B', textEs: 'dice', textHy: 'ասում է (él/ella)' },
      { key: 'C', textEs: 'dices', textHy: 'ասում ես (tú)' },
      { key: 'D', textEs: 'decimos', textHy: 'ասում ենք (nosotros)' },
    ],
    correct: 'B',
    explanationHy: '«El entrenador»-ը él է, ուստի «decir» (e -> i) բայը դառնում է «dice» (ասում է)։',
    hintHy: 'Decir բայը 3-րդ դեմքում (él) փոխում է e-ն i-ի՝ dice:',
    prizeValue: 50000,
  },

  // --- Ronda 3 — Situaciones en el campo (13-18) ---
  {
    id: 13,
    part: 3,
    partTitleEs: 'Ronda 3 — Situaciones en el campo',
    partTitleHy: 'Փուլ 3 — Իրավիճակներ դաշտում (Situaciones en el campo)',
    questionEs: 'El partido _____ a las cinco de la tarde.',
    questionHy: 'Խաղը սկսվում է երեկոյան ժամը հինգին։',
    verb: 'empezar',
    options: [
      { key: 'A', textEs: 'empiezo', textHy: 'սկսում եմ (yo)' },
      { key: 'B', textEs: 'empiezas', textHy: 'սկսում ես (tú)' },
      { key: 'C', textEs: 'empieza', textHy: 'սկսվում է (él/ella)' },
      { key: 'D', textEs: 'empezamos', textHy: 'սկսում ենք (nosotros)' },
    ],
    correct: 'C',
    explanationHy: '«El partido»-ն (խաղը) 3-րդ դեմք է (él), ուստի «empezar» (e -> ie) բայը դառնում է «empieza»։',
    hintHy: '«Խաղը» (él) պահանջում է empieza (e -> ie):',
    prizeValue: 75000,
  },
  {
    id: 14,
    part: 3,
    partTitleEs: 'Ronda 3 — Situaciones en el campo',
    partTitleHy: 'Փուլ 3 — Իրավիճակներ դաշտում (Situaciones en el campo)',
    questionEs: 'Después del entrenamiento, los jugadores _____ a casa.',
    questionHy: 'Մարզումից հետո ֆուտբոլիստները վերադառնում են տուն։',
    verb: 'volver',
    options: [
      { key: 'A', textEs: 'vuelven', textHy: 'վերադառնում են (ellos)' },
      { key: 'B', textEs: 'volvemos', textHy: 'վերադառնում ենք (nosotros)' },
      { key: 'C', textEs: 'vuelvo', textHy: 'վերադառնում եմ (yo)' },
      { key: 'D', textEs: 'vuelve', textHy: 'վերադառնում է (él/ella)' },
    ],
    correct: 'A',
    explanationHy: '«Los jugadores»-ը (ֆուտբոլիստները) ellos են, «volver» (o -> ue) բայը դառնում է «vuelven»։',
    hintHy: 'Հոգնակի 3-րդ դեմքն է (ellos)՝ vuelven (o -> ue):',
    prizeValue: 100000,
  },
  {
    id: 15,
    part: 3,
    partTitleEs: 'Ronda 3 — Situaciones en el campo',
    partTitleHy: 'Փուլ 3 — Իրավիճակներ դաշտում (Situaciones en el campo)',
    questionEs: 'Mi mejor amigo _____ muy rápido cuando juega al fútbol.',
    questionHy: 'Իմ լավագույն ընկերը շատ արագ է վազում, երբ ֆուտբոլ է խաղում։',
    verb: 'correr',
    options: [
      { key: 'A', textEs: 'corro', textHy: 'վազում եմ (yo)' },
      { key: 'B', textEs: 'corres', textHy: 'վազում ես (tú)' },
      { key: 'C', textEs: 'corremos', textHy: 'վազում ենք (nosotros)' },
      { key: 'D', textEs: 'corre', textHy: 'վազում է (él/ella)' },
    ],
    correct: 'D',
    explanationHy: '«Mi mejor amigo»-ն él է, ուստի «correr» կանոնավոր բայը 3-րդ դեմքում ստանում է «corre» ձևը։',
    hintHy: '«Mi mejor amigo» (նա/él) ստանում է «-e» վերջավորություն՝ corre:',
    prizeValue: 125000,
  },
  {
    id: 16,
    part: 3,
    partTitleEs: 'Ronda 3 — Situaciones en el campo',
    partTitleHy: 'Փուլ 3 — Իրավիճակներ դաշտում (Situaciones en el campo)',
    questionEs: 'Yo _____ mis botas de fútbol antes de salir.',
    questionHy: 'Ես հագնում եմ ֆուտբոլային խաղակոշիկներս՝ դուրս գալուց առաջ։',
    verb: 'poner',
    options: [
      { key: 'A', textEs: 'pones', textHy: 'հագնում/դնում ես (tú)' },
      { key: 'B', textEs: 'pongo', textHy: 'հագնում/դնում եմ (yo)' },
      { key: 'C', textEs: 'pone', textHy: 'հագնում/դնում է (él/ella)' },
      { key: 'D', textEs: 'ponemos', textHy: 'հագնում/դնում ենք (nosotros)' },
    ],
    correct: 'B',
    explanationHy: '«Yo» (ես) դերանվան հետ «poner» բայը ներկայում անկանոն է՝ «pongo» (հագնում/դնում եմ)։',
    hintHy: 'Poner բայի 1-ին դեմքն է (yo) «pongo»:',
    prizeValue: 150000,
  },
  {
    id: 17,
    part: 3,
    partTitleEs: 'Ronda 3 — Situaciones en el campo',
    partTitleHy: 'Փուլ 3 — Իրավիճակներ դաշտում (Situaciones en el campo)',
    questionEs: '¿Vosotros _____ las instrucciones del entrenador?',
    questionHy: 'Դուք հասկանո՞ւմ եք մարզչի հրահանգները։',
    verb: 'entender',
    options: [
      { key: 'A', textEs: 'entiendo', textHy: 'հասկանում եմ (yo)' },
      { key: 'B', textEs: 'entiende', textHy: 'հասկանում է (él/ella)' },
      { key: 'C', textEs: 'entendéis', textHy: 'հասկանում եք (vosotros)' },
      { key: 'D', textEs: 'entienden', textHy: 'հասկանում են (ellos)' },
    ],
    correct: 'C',
    explanationHy: '«Vosotros» (դուք) դերանվան հետ «entender» բայի ձևն է «entendéis» (vosotros-ի դեպքում արմատային e-ն չի փոխվում)։',
    hintHy: 'Vosotros-ի վերջավորությունն է «-éis»՝ entendéis:',
    prizeValue: 175000,
  },
  {
    id: 18,
    part: 3,
    partTitleEs: 'Ronda 3 — Situaciones en el campo',
    partTitleHy: 'Փուլ 3 — Իրավիճակներ դաշտում (Situaciones en el campo)',
    questionEs: 'Nuestro equipo _____ entrenando aunque está cansado.',
    questionHy: 'Մեր թիմը շարունակում է մարզվել, չնայած հոգնած է։',
    verb: 'seguir',
    options: [
      { key: 'A', textEs: 'sigue', textHy: 'շարունակում է (él/ella)' },
      { key: 'B', textEs: 'sigo', textHy: 'շարունակում եմ (yo)' },
      { key: 'C', textEs: 'seguimos', textHy: 'շարունակում ենք (nosotros)' },
      { key: 'D', textEs: 'siguen', textHy: 'շարունակում են (ellos)' },
    ],
    correct: 'A',
    explanationHy: '«Nuestro equipo»-ն (մեր թիմը) եզակի գոյական է (él), «seguir» (e -> i) բայը դառնում է «sigue»։',
    hintHy: '«Nuestro equipo» (թիմը) եզակի 3-րդ դեմք է՝ sigue:',
    prizeValue: 200000,
    isMilestone: true,
  },

  // --- Ronda 4 — El día de un futbolista (19-24) ---
  {
    id: 19,
    part: 4,
    partTitleEs: 'Ronda 4 — El día de un futbolista',
    partTitleHy: 'Փուլ 4 — Ֆուտբոլիստի առօրյան (El día de un futbolista)',
    questionEs: 'Los futbolistas _____ ocho horas por la noche.',
    questionHy: 'Ֆուտբոլիստները գիշերը քնում են ութ ժամ։',
    verb: 'dormir',
    options: [
      { key: 'A', textEs: 'duermo', textHy: 'քնում եմ (yo)' },
      { key: 'B', textEs: 'duerme', textHy: 'քնում է (él/ella)' },
      { key: 'C', textEs: 'dormimos', textHy: 'քնում ենք (nosotros)' },
      { key: 'D', textEs: 'duermen', textHy: 'քնում են (ellos)' },
    ],
    correct: 'D',
    explanationHy: '«Los futbolistas»-ը ellos են, ուստի «dormir» (o -> ue) բայը դառնում է «duermen» (քնում են)։',
    hintHy: 'Հոգնակի 3-րդ դեմքն է (ellos)՝ duermen (o -> ue):',
    prizeValue: 250000,
  },
  {
    id: 20,
    part: 4,
    partTitleEs: 'Ronda 4 — El día de un futbolista',
    partTitleHy: 'Փուլ 4 — Ֆուտբոլիստի առօրյան (El día de un futbolista)',
    questionEs: 'Yo _____ en Madrid y entreno todos los días.',
    questionHy: 'Ես ապրում եմ Մադրիդում և ամեն օր մարզվում եմ։',
    verb: 'vivir',
    options: [
      { key: 'A', textEs: 'vives', textHy: 'ապրում ես (tú)' },
      { key: 'B', textEs: 'vivo', textHy: 'ապրում եմ (yo)' },
      { key: 'C', textEs: 'vive', textHy: 'ապրում է (él/ella)' },
      { key: 'D', textEs: 'vivimos', textHy: 'ապրում ենք (nosotros)' },
    ],
    correct: 'B',
    explanationHy: '«Yo» (ես) դերանվան հետ «vivir» կանոնավոր բայը ստանում է «vivo» ձևը (ապրում եմ)։',
    hintHy: '«Yo»-ի հետ բայի վերջավորությունն է «-o»՝ vivo:',
    prizeValue: 300000,
  },
  {
    id: 21,
    part: 4,
    partTitleEs: 'Ronda 4 — El día de un futbolista',
    partTitleHy: 'Փուլ 4 — Ֆուտբոլիստի առօրյան (El día de un futbolista)',
    questionEs: 'Mi entrenador _____ los partidos por televisión.',
    questionHy: 'Իմ մարզիչը հեռուստացույցով դիտում է խաղերը։',
    verb: 'ver',
    options: [
      { key: 'A', textEs: 'veo', textHy: 'դիտում եմ (yo)' },
      { key: 'B', textEs: 'vemos', textHy: 'դիտում ենք (nosotros)' },
      { key: 'C', textEs: 've', textHy: 'դիտում է (él/ella)' },
      { key: 'D', textEs: 'ves', textHy: 'դիտում ես (tú)' },
    ],
    correct: 'C',
    explanationHy: '«Mi entrenador»-ը él է, ուստի «ver» (դիտել/տեսնել) բայը դառնում է «ve»։',
    hintHy: '«Mi entrenador» (նա/él) ստանում է «ve» ձևը:',
    prizeValue: 350000,
  },
  {
    id: 22,
    part: 4,
    partTitleEs: 'Ronda 4 — El día de un futbolista',
    partTitleHy: 'Փուլ 4 — Ֆուտբոլիստի առօրյան (El día de un futbolista)',
    questionEs: 'Nosotros _____ música antes del partido.',
    questionHy: 'Մենք խաղից առաջ երաժշտություն ենք լսում։',
    verb: 'escuchar',
    options: [
      { key: 'A', textEs: 'escuchamos', textHy: 'լսում ենք (nosotros)' },
      { key: 'B', textEs: 'escuchan', textHy: 'լսում են (ellos)' },
      { key: 'C', textEs: 'escucho', textHy: 'լսում եմ (yo)' },
      { key: 'D', textEs: 'escucha', textHy: 'լսում է (él/ella)' },
    ],
    correct: 'A',
    explanationHy: '«Nosotros»-ի հետ «escuchar» (-ar) բայը ստանում է «-amos» վերջավորությունը՝ «escuchamos»։',
    hintHy: '«Nosotros»-ի հետ -ar բայերը ստանում են «-amos»՝ escuchamos:',
    prizeValue: 400000,
  },
  {
    id: 23,
    part: 4,
    partTitleEs: 'Ronda 4 — El día de un futbolista',
    partTitleHy: 'Փուլ 4 — Ֆուտբոլիստի առօրյան (El día de un futbolista)',
    questionEs: 'Cuando tengo una pregunta, _____ ayuda al entrenador.',
    questionHy: 'Երբ հարց եմ ունենում, մարզչից օգնություն եմ խնդրում։',
    verb: 'pedir',
    options: [
      { key: 'A', textEs: 'pides', textHy: 'խնդրում ես (tú)' },
      { key: 'B', textEs: 'pide', textHy: 'խնդրում է (él/ella)' },
      { key: 'C', textEs: 'pedimos', textHy: 'խնդրում ենք (nosotros)' },
      { key: 'D', textEs: 'pido', textHy: 'խնդրում եմ (yo)' },
    ],
    correct: 'D',
    explanationHy: '«Cuando tengo...» (երբ ես ունեմ) ցույց է տալիս yo դեմքը, իսկ «pedir» (e -> i) բայը դառնում է «pido» (խնդրում եմ)։',
    hintHy: 'Խոսքը 1-ին դեմքի (yo) մասին է՝ pido (e -> i):',
    prizeValue: 450000,
  },
  {
    id: 24,
    part: 4,
    partTitleEs: 'Ronda 4 — El día de un futbolista',
    partTitleHy: 'Փուլ 4 — Ֆուտբոլիստի առօրյան (El día de un futbolista)',
    questionEs: 'Los compañeros _____ a los jugadores nuevos.',
    questionHy: 'Թիմակիցները օգնում են նոր ֆուտբոլիստներին։',
    verb: 'ayudar',
    options: [
      { key: 'A', textEs: 'ayuda', textHy: 'օգնում է (él/ella)' },
      { key: 'B', textEs: 'ayudan', textHy: 'օգնում են (ellos)' },
      { key: 'C', textEs: 'ayudamos', textHy: 'օգնում ենք (nosotros)' },
      { key: 'D', textEs: 'ayudas', textHy: 'օգնում ես (tú)' },
    ],
    correct: 'B',
    explanationHy: '«Los compañeros»-ը (թիմակիցները) ellos են, «ayudar» բայի ձևն է «ayudan» (օգնում են)։',
    hintHy: 'Հոգնակի 3-րդ դեմք (ellos) -> -an վերջավորություն՝ ayudan:',
    prizeValue: 500000,
  },

  // --- Ronda 5 — El reto del campeón (25-30) ---
  {
    id: 25,
    part: 5,
    partTitleEs: 'Ronda 5 — El reto del campeón',
    partTitleHy: 'Փուլ 5 — Չեմպիոնի փորձությունը (El reto del campeón)',
    questionEs: '¿Dónde _____ tus compañeros ahora?',
    questionHy: 'Որտե՞ղ են հիմա քո թիմակիցները։',
    verb: 'estar',
    options: [
      { key: 'A', textEs: 'están', textHy: 'գտնվում են (ellos - estar)' },
      { key: 'B', textEs: 'somos', textHy: 'ենք (nosotros - ser)' },
      { key: 'C', textEs: 'está', textHy: 'գտնվում է (él/ella - estar)' },
      { key: 'D', textEs: 'es', textHy: 'է (él/ella - ser)' },
    ],
    correct: 'A',
    explanationHy: 'Գտնվելու վայրի (¿Dónde...?) և հոգնակի 3-րդ դեմքի (tus compañeros) համար գործածվում է «estar» բայի «están» ձևը։',
    hintHy: 'Վայր արտահայտելու համար օգտագործվում է estar, իսկ թիմակիցները ellos են՝ están:',
    prizeValue: 600000,
  },
  {
    id: 26,
    part: 5,
    partTitleEs: 'Ronda 5 — El reto del campeón',
    partTitleHy: 'Փուլ 5 — Չեմպիոնի փորձությունը (El reto del campeón)',
    questionEs: 'Nuestro equipo normalmente _____ los partidos en casa.',
    questionHy: 'Մեր թիմը սովորաբար հաղթում է տնային խաղերում։',
    verb: 'ganar',
    options: [
      { key: 'A', textEs: 'gano', textHy: 'հաղթում եմ (yo)' },
      { key: 'B', textEs: 'ganamos', textHy: 'հաղթում ենք (nosotros)' },
      { key: 'C', textEs: 'gana', textHy: 'հաղթում է (él/ella)' },
      { key: 'D', textEs: 'ganan', textHy: 'հաղթում են (ellos)' },
    ],
    correct: 'C',
    explanationHy: '«Nuestro equipo»-ն (մեր թիմը) եզակի 3-րդ դեմք է (él), ուստի «ganar» բայը դառնում է «gana» (հաղթում է)։',
    hintHy: '«Nuestro equipo» (թիմը) եզակի գոյական է՝ gana:',
    prizeValue: 700000,
  },
  {
    id: 27,
    part: 5,
    partTitleEs: 'Ronda 5 — El reto del campeón',
    partTitleHy: 'Փուլ 5 — Չեմպիոնի փորձությունը (El reto del campeón)',
    questionEs: 'Cuando nuestro equipo _____, estamos tristes.',
    questionHy: 'Երբ մեր թիմը պարտվում է, մենք տխրում ենք։',
    verb: 'perder',
    options: [
      { key: 'A', textEs: 'pierdo', textHy: 'պարտվում եմ (yo)' },
      { key: 'B', textEs: 'pierdes', textHy: 'պարտվում ես (tú)' },
      { key: 'C', textEs: 'perdemos', textHy: 'պարտվում ենք (nosotros)' },
      { key: 'D', textEs: 'pierde', textHy: 'պարտվում է (él/ella)' },
    ],
    correct: 'D',
    explanationHy: '«Nuestro equipo»-ն él է, «perder» (e -> ie) բայը դառնում է «pierde» (պարտվում է)։',
    hintHy: '«Nuestro equipo» (él) պահանջում է pierde (e -> ie):',
    prizeValue: 800000,
  },
  {
    id: 28,
    part: 5,
    partTitleEs: 'Ronda 5 — El reto del campeón',
    partTitleHy: 'Փուլ 5 — Չեմպիոնի փորձությունը (El reto del campeón)',
    questionEs: 'Yo _____ jugar de centrocampista porque me gusta dar pases.',
    questionHy: 'Ես նախընտրում եմ խաղալ կիսապաշտպանի դիրքում, որովհետև սիրում եմ փոխանցումներ կատարել։',
    verb: 'preferir',
    options: [
      { key: 'A', textEs: 'prefieres', textHy: 'նախընտրում ես (tú)' },
      { key: 'B', textEs: 'prefiero', textHy: 'նախընտրում եմ (yo)' },
      { key: 'C', textEs: 'prefiere', textHy: 'նախընտրում է (él/ella)' },
      { key: 'D', textEs: 'preferimos', textHy: 'նախընտրում ենք (nosotros)' },
    ],
    correct: 'B',
    explanationHy: '«Yo» (ես) դերանվան հետ «preferir» (e -> ie) բայը դառնում է «prefiero» (նախընտրում եմ)։',
    hintHy: '«Yo»-ի հետ preferir բայն ունի «-o» վերջավորություն՝ prefiero:',
    prizeValue: 900000,
  },
  {
    id: 29,
    part: 5,
    partTitleEs: 'Ronda 5 — El reto del campeón',
    partTitleHy: 'Փուլ 5 — Չեմպիոնի փորձությունը (El reto del campeón)',
    questionEs: 'Mi hermano _____ del entrenamiento a las siete.',
    questionHy: 'Եղբայրս մարզումից դուրս է գալիս ժամը յոթին։',
    verb: 'salir',
    options: [
      { key: 'A', textEs: 'sale', textHy: 'դուրս է գալիս (él/ella)' },
      { key: 'B', textEs: 'salgo', textHy: 'դուրս եմ գալիս (yo)' },
      { key: 'C', textEs: 'sales', textHy: 'դուրս ես գալիս (tú)' },
      { key: 'D', textEs: 'salimos', textHy: 'դուրս ենք գալիս (nosotros)' },
    ],
    correct: 'A',
    explanationHy: '«Mi hermano»-ն (եղբայրս) él է, ուստի «salir» բայը 3-րդ դեմքում դառնում է «sale» (դուրս է գալիս)։',
    hintHy: '«Mi hermano» (él) ստանում է «sale» ձևը (սովորական -ir վերջավորություն):',
    prizeValue: 950000,
  },
  {
    id: 30,
    part: 5,
    partTitleEs: 'Ronda 5 — El reto del campeón',
    partTitleHy: 'Փուլ 5 — Չեմպիոնի փորձությունը (El reto del campeón)',
    questionEs: '¿Quién _____ a los jugadores para el próximo partido?',
    questionHy: 'Ո՞վ է ընտրում ֆուտբոլիստներին հաջորդ խաղի համար։',
    verb: 'elegir',
    options: [
      { key: 'A', textEs: 'elijo', textHy: 'ընտրում եմ (yo)' },
      { key: 'B', textEs: 'eliges', textHy: 'ընտրում ես (tú)' },
      { key: 'C', textEs: 'elige', textHy: 'ընտրում է (él/ella)' },
      { key: 'D', textEs: 'elegimos', textHy: 'ընտրում ենք (nosotros)' },
    ],
    correct: 'C',
    explanationHy: '«¿Quién...?» (ո՞վ) հարցական դերանունը միշտ պահանջում է եզակի 3-րդ դեմք, «elegir» (e -> i) բայը դառնում է «elige»։',
    hintHy: '«Quién» (ո՞վ) հարցը պահանջում է եզակի 3-րդ դեմք (él)՝ elige (e -> i):',
    prizeValue: 1000000,
    isMilestone: true,
  },
];
